### ISSUE TITLE
Are there server test results available?

### ISSUE THREAD

**Issue by smares** [andydavies/http2-prioritization-issues#19]
### Summary
The README says:

> Most servers technically support HTTP/2 prioritisation

Are there test results available, maybe even including software like Traefik?

### Server / CDN etc.
n/a

### Browser
n/a

### Link to WebPageTest result
n/a

### Link to  upstream bug report
n/a

**Comment by andydavies** [comment]
Test results are either ones we've run ourselves or submitted by others.

No-one's submitted test results for any of the servers ATM

**Comment by pmeenan** [comment]
Server tests are not going to be terribly useful because it is going to be installation-specific. It takes a lot more than just server support for prioritization to work.  Best case for the server section would be to document each server, if it supports prioritization and what it takes to get it working.
